### ISSUE TITLE
内容过多的时候会产生oom

### ISSUE THREAD

**Issue by lpy19930103** [REBOOTERS/AndroidAnimationExercise#1]
内容过多的时候会产生oom
java.lang.OutOfMemoryError: Failed to allocate a 75311756 byte allocation with 15657184 free bytes and 14MB until OOM

**Comment by REBOOTERS** [comment]
这个项目的初衷就是不断累积平时练习的demo，随着时间推移，内容增多是必然的事情，不知道你所说的OOM 是在特定的某个页面，还是说运行时发生。
