### ISSUE TITLE
无法下载apk，404

### ISSUE THREAD

**Issue by JDNew** [REBOOTERS/AndroidAnimationExercise#12]

**Comment by REBOOTERS** [comment]
感谢反馈，readme 已更新。

**Comment by JDNew** [comment]
现在网址可以打开，但我这里还是下载不了......

**Comment by REBOOTERS** [comment]
> 现在网址可以打开，但我这里还是下载不了...... @REBOOTERS

我试了一下，是可以的呀。托管地址： http://d.7short.com/tm15 里如果无法下载，可能就是网络的原因了。😢
