### ISSUE TITLE
app 打不开啊

### ISSUE THREAD

**Issue by zhengjieAdriod** [REBOOTERS/AndroidAnimationExercise#2]
app 打不开啊

**Comment by REBOOTERS** [comment]
打不开是什么意思，是无法启动吗？用的什么手机，什么系统？

**Comment by zhengjieAdriod** [comment]
oppo a53    5.1.1

**Comment by zhengjieAdriod** [comment]
点击启动   直接退出了

**Comment by zhengjieAdriod** [comment]
也就是说打不开页面

**Comment by REBOOTERS** [comment]
可以看看日志，有什么报错吗？

**Comment by zhengjieAdriod** [comment]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference

**Comment by zhengjieAdriod** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{home.smart.fly.animations/home.smart.fly.animations.AppStartActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference

**Comment by zhengjieAdriod** [comment]
刚刚用  华为a03l    5.1.1  也不行

**Comment by REBOOTERS** [comment]
`        String filepath = Environment.getExternalStorageDirectory().getAbsolutePath();
        //
        String getDataDirectory = Environment.getDataDirectory().getAbsolutePath();
        String getRootDirectory = Environment.getRootDirectory().getAbsolutePath();
        String getDownloadCacheDirectory = Environment.getDownloadCacheDirectory().getAbsolutePath();
        //
        String DIRECTORY_DCIM = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DCIM).getAbsolutePath();
        String DIRECTORY_DOCUMENTS = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS).getAbsolutePath();
        String DIRECTORY_PICTURES = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES).getAbsolutePath();
        String DIRECTORY_DOWNLOADS = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).getAbsolutePath();
        //
        String cacheDir = mContext.getCacheDir().getAbsolutePath();
        String filesDir = mContext.getFilesDir().getAbsolutePath();
        //
        String getExternalCacheDir = mContext.getExternalCacheDir().getAbsolutePath();
        String getExternalFilesDir_DIRECTORY_PICTURES = mContext.getExternalFilesDir(Environment.DIRECTORY_PICTURES).getAbsolutePath();
        String getExternalFilesDir_DIRECTORY_DOCUMENTS = mContext.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS).getAbsolutePath();


        String[] files = new String[mContext.getExternalCacheDirs().length];
        for (int i = 0; i < mContext.getExternalCacheDirs().length; i++) {
            File mFile = mContext.getExternalCacheDirs()[i];
            files[i] = mFile.getAbsolutePath() + "\n";
        }`

AppStartActivity 里有这样一些打印系统目录结构的日志，我也不知道你的手机上哪个目录，没有获取到，Android手机碎片化的问题实在是无能为力；如果感兴趣，自己用源码跑一下，看看是哪里报错吧！

**Comment by zhengjieAdriod** [comment]
好的...
