### ISSUE TITLE
运行项目出错

### ISSUE THREAD

**Issue by kokobebekoko** [REBOOTERS/AndroidAnimationExercise#5]
Illegal char <:> at index 137: F:\AndroidStudioProjects\AndroidAnimationExercise-master\app\build\intermediates\instant-run-apk\charge\debug\animation-3.0-2018-10-07 13:20-chargeDebug.apk

**Comment by REBOOTERS** [comment]
嗯，看来是 instant-run 的问题，平时运行都是关闭 instant-run ，我这边试一下

**Comment by kokobebekoko** [comment]
> 嗯，看来是 instant-run 的问题，平时运行都是关闭 instant-run ，我这边试一下

我一开始也认为这个问题 后面关了也不行

**Comment by kokobebekoko** [comment]
> 你是？在哪运行出现的问题？发自我的华为手机-------- 原始邮件 --------主题：Re: [REBOOTERS/AndroidAnimationExercise] 运行项目出错 (#5)发件人：Rookie 收件人：REBOOTERS/AndroidAnimationExercise 抄送：Subscribed 嗯，看来是 instant-run 的问题，平时运行都是关闭 instant-run ，我这边试一下 —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

AS啊 这没什么疑问吧

**Comment by timizhuoym** [comment]
你是AS官方是吗？我还以为我代码泄露了，这个是我的哪里出现问题了吗？请问发自我的华为手机-------- 原始邮件 --------主题：Re: [REBOOTERS/AndroidAnimationExercise] 运行项目出错 (#5)发件人：kokobebekoko 收件人：REBOOTERS/AndroidAnimationExercise 抄送：timizhuoym <2049525995@qq.com>,Comment 
你是？在哪运行出现的问题？发自我的华为手机-------- 原始邮件 --------主题：Re: [REBOOTERS/AndroidAnimationExercise] 运行项目出错 (#5)发件人：Rookie 收件人：REBOOTERS/AndroidAnimationExercise 抄送：Subscribed 嗯，看来是 instant-run 的问题，平时运行都是关闭 instant-run ，我这边试一下 —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

AS啊 这没什么疑问吧

**Comment by REBOOTERS** [comment]
我这边打开 instant-run 也是没有问题，难道是 Android  Studio  版本的问题吗？以下是我用的版本，也就是官方最新版本


![image](https://user-images.githubusercontent.com/7893197/46648379-854ac380-cbc7-11e8-956e-e9c63e75cd76.png)

**Comment by timizhuoym** [comment]
我现在也可以正常运行，用的AS也是3.2.0，gradle是4.10，jdk是1.8发自我的华为手机-------- 原始邮件 --------主题：Re: [REBOOTERS/AndroidAnimationExercise] 运行项目出错 (#5)发件人：Rookie 收件人：REBOOTERS/AndroidAnimationExercise 抄送：timizhuoym <2049525995@qq.com>,Comment 我这边打开 instant-run 也是没有问题，难道是 Android  Studio  版本的问题吗？以下是我用的版本，也就是官方最新版本

**Comment by kokobebekoko** [comment]
> 我这边打开 instant-run 也是没有问题，难道是 Android Studio 版本的问题吗？以下是我用的版本，也就是官方最新版本
> 
> ![image](https://user-images.githubusercontent.com/7893197/46648379-854ac380-cbc7-11e8-956e-e9c63e75cd76.png)
> 
> @kokobebekoko @timizhuoym

我是AS 3.1 gradle 3.1.2 运行报错

**Comment by kokobebekoko** [comment]
![image](https://user-images.githubusercontent.com/5987097/46649165-9c3ee500-cbca-11e8-9b61-865d7f39bdcc.png)

**Comment by kokobebekoko** [comment]
![image](https://user-images.githubusercontent.com/5987097/46649254-06578a00-cbcb-11e8-820a-cbec4428e56b.png)

**Comment by REBOOTERS** [comment]
升级看看吧，反正都是稳定版了

**Comment by kokobebekoko** [comment]
> 升级看看吧，反正都是稳定版了

你这个项目只运行在3.2吗？

**Comment by timizhuoym** [comment]
从2.2慢慢升上去的发自我的华为手机-------- 原始邮件 --------主题：Re: [REBOOTERS/AndroidAnimationExercise] 运行项目出错 (#5)发件人：kokobebekoko 收件人：REBOOTERS/AndroidAnimationExercise 抄送：timizhuoym <2049525995@qq.com>,Mention 
升级看看吧，反正都是稳定版了

你这个项目只运行在3.2吗？

**Comment by timizhuoym** [comment]
好的发自我的华为手机-------- 原始邮件 --------主题：Re: [REBOOTERS/AndroidAnimationExercise] 运行项目出错 (#5)发件人：kokobebekoko 收件人：REBOOTERS/AndroidAnimationExercise 抄送：timizhuoym <2049525995@qq.com>,Mention 
升级看看吧，反正都是稳定版了

你这个项目只运行在3.2吗？

**Comment by kokobebekoko** [comment]
> 升级看看吧，反正都是稳定版了

升级了 仍然不行 as 3.2 gradle 3.2.0
![image](https://user-images.githubusercontent.com/5987097/46675584-55281280-cc11-11e8-8a32-d4a0c40f006f.png)

**Comment by REBOOTERS** [comment]
> > 升级看看吧，反正都是稳定版了
> 
> 升级了 仍然不行 as 3.2 gradle 3.2.0
> ![image](https://user-images.githubusercontent.com/5987097/46675584-55281280-cc11-11e8-8a32-d4a0c40f006f.png)

gradle 3.2 是什么鬼？ 使用 AS 3.2 gradle 不得升到4.6吗？

**Comment by kokobebekoko** [comment]
> > > 升级看看吧，反正都是稳定版了
> > 
> > 
> > 升级了 仍然不行 as 3.2 gradle 3.2.0
> > ![image](https://user-images.githubusercontent.com/5987097/46675584-55281280-cc11-11e8-8a32-d4a0c40f006f.png)
> 
> gradle 3.2 是什么鬼？ 使用 AS 3.2 gradle 不得升到4.6吗？

解决了，屏蔽Gradle一句关于生成output APK的代码 解决问题

**Comment by timizhuoym** [comment]
谢谢发自我的华为手机-------- 原始邮件 --------主题：Re: [REBOOTERS/AndroidAnimationExercise] 运行项目出错 (#5)发件人：kokobebekoko 收件人：REBOOTERS/AndroidAnimationExercise 抄送：timizhuoym <2049525995@qq.com>,Mention 


升级看看吧，反正都是稳定版了

升级了 仍然不行 as 3.2 gradle 3.2.0


gradle 3.2 是什么鬼？ 使用 AS 3.2 gradle 不得升到4.6吗？

解决了，屏蔽Gradle一句关于生成output APK的代码 解决问题

**Comment by REBOOTERS** [comment]
恩，应该是代码没有及时更新的问题
