### ISSUE TITLE
apk下载后无法安装

### ISSUE THREAD

**Issue by faith-hb** [REBOOTERS/AndroidAnimationExercise#7]

**Comment by REBOOTERS** [comment]
是如何安装的呢？ 有什么报错信息吗？

**Comment by Yedongsheng** [comment]
安装失败，提示：
（1）无效安装包
（2）与操作系统不兼容

**Comment by REBOOTERS** [comment]
@Yedongsheng 是什么系统呢？

**Comment by caizhixing** [comment]
提示 该软件包似乎已损坏  小米 MIUI 9.5

**Comment by liuhuiAndroid** [comment]
![image](https://user-images.githubusercontent.com/12246679/56275652-b5a18a80-6133-11e9-98bd-690df10c107e.png)

**Comment by liuhuiAndroid** [comment]
华为手机 Android 9 ，EMUI 9.0 安装失败

**Comment by Passion-long** [comment]
红米note4X安装失败

**Comment by REBOOTERS** [comment]
@faith-hb @Yedongsheng @caizhixing @liuhuiAndroid @Passion-long 

安装包已更新，测试了一下，现在可以安装了。
